name: build and publish

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created


jobs:
  build-publish:
    uses: decentraland/platform-actions/.github/workflows/libs-build-and-publish.yml@main
    secrets:
      SDK_TEAM_S3_BUCKET: ${{ secrets.SDK_TEAM_S3_BUCKET }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_URL: ${{ secrets.GITLAB_URL }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SDK_TEAM_AWS_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
      SDK_TEAM_AWS_SECRET: ${{ secrets.SDK_TEAM_AWS_SECRET }}
      SDK_TEAM_S3_BASE_URL: ${{ secrets.SDK_TEAM_S3_BASE_URL }}
      SDK_TEAM_AWS_REGION: ${{ secrets.SDK_TEAM_AWS_REGION }}
