name: build and publish

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

jobs:
  build-publish:
    uses: decentraland/platform-actions/.github/workflows/libs-build-and-publish.yml@main
