on:
  push:
    branches:
      - master

name: Release and publish NPM package
jobs:

  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  release:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build-and-test
    if: ${{ success() }}
    steps:
      - uses: decentraland/gh-action-release@0.3.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: get latest release and export as GIT_TAG
        run:  echo "GIT_TAG=$(git tag | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | sort -V | tail -1)" > $GITHUB_ENV
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - name: Install node dependencies
        run: npm install
      - name: Update catalyst list
        run: npm run catalysts-list
      - name: Build library
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: NPM Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
